# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b78d9cfc0562b759342803808133dbda2a9702686d9a97b5e628076225b1b3aeb8053cb9db86510d0568954f8006569ccdf329973bb6a7a7eecebe8f54d13eab

test:
  secret_key_base: 8d7c34ec3d38479c6c44a14141cf9bbb605ffce0c850c4d55b9c5775e46c2a5676027eea0fd1eb633485793b5bdf9c2249908c459b246bcb448945e38487d11c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
